#checkoutLocation: "st-apps"
#workspaceLocation: "."
#github:
##  prebuilds:
#    main: true
tasks:
  - before: echo 'export PIP_USER=no' >> ~/.bashrc && source ~/.bashrc
  - init: pip install poetry && poetry config virtualenvs.create false && poetry config virtualenvs.in-project true && poetry env use python && poetry install
vscode:
  extensions:
    - ms-python.python
gitConfig:
  alias.st: status
  alias.cm: commit
  core.autocrlf: input