deploy:
	gcloud run deploy bigquery-search \
	--source bigquery-search \
	--region "asia-norcheast1" \
	--platform managed
	
help:
	@echo "Usage: make [target]"
	@echo "Targets:"
	@echo "  deploy: Deploy the application to Google Cloud Run"
	@echo "  help:   Show this help message"
